@echo off
cls
echo  ÿ
echo  ÿ
echo    °°°±±±±²²²²²        Welcome to the CD-ROM version of        ²²²²²±±±±°°°
echo    °°°±±±±²²²²²   WIZARDRY VII - CRUSADERS OF THE DARK SAVANT  ²²²²²±±±±°°°
echo    ÿ
echo    This game plays directly from the CD-ROM. Configuration files and games
echo    are saved on your computer's hard disk drive using a minimum of space.
echo    ÿ
echo       To install Wizardry, type INSTALL D from your CD-ROM drive prompt.
echo ÿ  
echo       Example.. D:\INSTALL D  where D:\ is your CD-ROM drive prompt
echo                                 and D   is your CD-ROM drive (no colon ":")
echo ÿ
echo    This command tells the install program that your CD-ROM drive is D.
echo    If your ROM drive is not D simply replace D with the appropriate letter. 
echo ÿ  ÿ                                  
echo    After installing, from the CD-ROM drive prompt type CD\W7 to change to 
echo    the W7 directory and type PLAY to start Wizardry. After the opening 
echo    credits, click on CONFIGURATION to do your hardware settings.   ÿ
echo ÿ
echo    There is a manual and a passwords document in the root of the CD-ROM.  ÿ
echo    Type MANUAL to see the manual and PW to see the passwords file.  ÿ
echo   ÿ                                   
echo    °°°±±±±²²²²²                Have fun playing                ²²²²²±±±±°°°
echo    °°°±±±±²²²²²   WIZARDRY VII - CRUSADERS OF THE DARK SAVANT  ²²²²²±±±±°°°
